name: Docker Image CI

on:
  workflow_dispatch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          push: true
          tags: meetd/dockerpublish-kubernetes:${{ github.sha }}
    # - name: Set up Kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: 'latest'

    # - name: Authenticate with AKS
    #   run: |
    #     az login
    #     az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER }}
    - name: Deploy to Kubernetes
      run: |
          pwd
          ls -R
          # kubectl apply -f k8s/k8s-deployment.yaml
          # kubectl set image deployment/dockerpublish-kubernetes-deployment dockerpublish-kubernetes=meetd/dockerpublish-kubernetes:${{ github.sha }} -n default
          # kubectl rollout status deployment/dockerpublish-kubernetes-deployment -n default
    # - name: Update Kubernetes Deployment
    #   run: |
    #     kubectl set image deployment/dockerpublish-kubernetes-deployment dockerpublish-kubernetes=meetd/dockerpublish-kubernetes:${{ github.sha }} -n default
    #     kubectl rollout status deployment/dockerpublish-kubernetes-deployment -n default
